# Generated by Django 3.1.7 on 2021-03-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20210320_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
