# Generated by Django 3.0 on 2021-03-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VarianceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variance_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Variance',
        ),
        migrations.DeleteModel(
            name='Variance',
        ),
        migrations.AddField(
            model_name='productvariance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='productvariance',
            name='variance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.VarianceType'),
        ),
        migrations.AddField(
            model_name='product',
            name='variances',
            field=models.ManyToManyField(through='products.ProductVariance', to='products.VarianceType'),
        ),
    ]
