# Generated by Django 3.0.6 on 2020-09-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='Contactno',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
