# Generated by Django 3.0.4 on 2020-09-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20200904_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsalesdetail',
            name='product_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
