# Generated by Django 3.0.6 on 2020-09-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20200902_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSalesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.PositiveIntegerField()),
                ('SaleQuantity', models.PositiveIntegerField()),
                ('Discount', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoiceno', models.CharField(max_length=50, unique=True)),
                ('Customername', models.CharField(max_length=250)),
                ('Invoicedate', models.DateField()),
                ('CustomerEmail', models.EmailField(blank=True, max_length=254)),
                ('Contactno', models.PositiveIntegerField(blank=True, unique=True)),
                ('Address', models.TextField(blank=True)),
                ('Invoicetype', models.CharField(max_length=50)),
                ('SubTotal', models.PositiveIntegerField()),
                ('Discount', models.PositiveIntegerField(blank=True)),
                ('Tax', models.PositiveIntegerField(blank=True)),
                ('Shippingcharge', models.PositiveIntegerField(blank=True)),
                ('Products', models.ManyToManyField(through='sales.ProductSalesDetail', to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productsalesdetail',
            name='Invoiceno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.SalesInvoice'),
        ),
        migrations.AddField(
            model_name='productsalesdetail',
            name='Pcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
