# Generated by Django 3.0.6 on 2020-09-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200903_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='Contactno',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='Discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='Shippingcharge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='Tax',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
