# Generated by Django 3.0.6 on 2020-09-03 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200902_1841'),
        ('sales', '0003_auto_20200903_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsalesdetail',
            name='Discount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='productsalesdetail',
            name='Pcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='Contactno',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='Discount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='Shippingcharge',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='Tax',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
