# Generated by Django 3.0.4 on 2020-09-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20200903_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsalesdetail',
            name='product_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productsalesdetail',
            name='product_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
