# Generated by Django 3.0.4 on 2020-09-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20200904_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsalesdetail',
            name='Invoiceno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetail', to='sales.SalesInvoice'),
        ),
    ]
