# Generated by Django 3.0.4 on 2020-09-02 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Code', models.CharField(max_length=50, unique=True)),
                ('Product_name', models.CharField(max_length=250)),
                ('Quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('Product_Desc', models.TextField()),
                ('Purchase_price', models.PositiveIntegerField()),
                ('Selling_price', models.PositiveIntegerField()),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('Product_Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Brand')),
                ('Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
