# Generated by Django 3.0.4 on 2020-10-01 20:21

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200902_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_image_file_name),
        ),
    ]
