# Generated by Django 3.1.7 on 2021-03-05 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201002_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='Manufacturing_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
