# Generated by Django 3.1.7 on 2021-03-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210305_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(choices=[(1, 'Size'), (2, 'Weight'), (3, 'Colour')])),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Manufacturing_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='product',
            name='Variance',
            field=models.ManyToManyField(to='products.Variance'),
        ),
    ]
