# Generated by Django 3.1.7 on 2021-03-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210305_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Barcode',
            field=models.ImageField(blank=True, upload_to='barcodes'),
        ),
    ]
